= OCamlCC:  Bazel-enabled OCaml toolchain
:toc: auto
:toclevels: 3

See the link:https://github.com/ocaml/ocaml[upstream repository] for the original OCaml README.

Latest doc changes: 01/09/2023

== News (01/09/2023)

This version includes many major changes.  See <<overview>> for details.

== Quickstart

1. Install Bazel.  Recommendation: link:https://github.com/bazelbuild/bazelisk[Bazelisk]

2. Clone link:https://github.com/obazl-repository/ocaml[this repo].

3. `cd` into the root directory of the cloned repo and run configure: `$ ./configure`

4. Build some compilers:

  $ bazel build bin:ocamlc.byte
  $ bazel build bin:ocamlopt.opt

5. Build some tools:

  $ bazel build tools:ocamldep.byte
  $ bazel build tools:ocamlobjinfo.opt

5. Run some of the queries demonstrated in
link:bzl/docs/queries.adoc[queries] to see what build targets are
available.

6. Build and store the baseline compilers (built using `boot/ocamlc`
and the current source code state), so they can be used to rebuild the
compilers after source code changes:

    $ bazel run boot:checkpoint

7. After running `boot:checkpoint`, edit some code and run some tests:

    $ bazel test testsuite/tests/basic:Boxedints_test   ## four tests, one for each compiler
    $ bazel test testsuite/tests/basic:Boxedints_vv_test   ## just the ocamlc.byte test
    $ bazel test testsuite/tests/basic:tests --test_tag_filters=vv ## all ocamlc.byte tests in pkg
+
Bazel has very strong test magic; see link:bzl/docs/testing.adoc[testing] for details.

8.  Take a look at the docs.  Start with link:bzl/docs/terminology[symbols & terminology]

To build debug or instrumented variants add `--//runtime:DEBUG`,
`--//runtime:CAML_INSTR`. See link:bzl/docs/debugging.adoc[debugging]
for more info.

The build code for using alternate CC toolchains and cross-compiling
has not yet been updated.


== Overview

This fork of the OCaml compiler toolset repository contains
Proof-of-Concept build programs written in Bazel. The code that builds
the tools and compilers is identical to the upstream code; however
some of the source code related to configuration has been reorganized.
The changes affect the preprocessing used to generate source code; it
does not change the source code itself.

The Bazel ruleset - which we may call `rules_ocamlcc` - is a
stripped-down, minimal version of the standard
link:https://github.com/obazl/rules_ocaml[rules_ocaml] ruleset. It
includes only the functionality required to build the compiler. This
means it contains no direct support for PPX processing or for
generalized namespaces (automatic renaming of subcomponents,
generation of resolver module), for example. Furthermore, since the
ruleset is heavily customized for the sole purpose of building the
OCaml compilers and tools, it is included in this repository and is
not intended for use as a free-standing ruleset.

Why use a minimal ruleset? Several reasons. Bootstrapping requires
some special support that is never needed for ordinary OCaml builds,
so we do not want to add that overhead to the standard ruleset. The
bootstrap ruleset is easy to understand and modify, so it serves as a
useful intro to the standard OBazl ruleset.

The build structure of the compilers is actually fairly
straightforward, in most places. It uses only a few namespaces (what
Dune calls a "wrapped" library), most prominently the Standard Library
(`Stdlib`), whose resolver (or "wrapper") module is hand-coded. The
bootstrapping process is a little more complicated, but
understandable. The most complicated part is probably the
preprocessing; but even the more complicated bits of preprocessing are
handled fairly easily by standard Bazel facilities. It involves C
interfacing. All of this makes this a useful starting point for people
interested in learning how to build OCaml software using Obazl.

Highlights:

Compiler build targets:: Previous versions defined a single
parameterized build target for the compilers: `//bin:ocamlcc
--config=ocamlc.byte`. This proved to be error-prone and difficult to
debug, so it has been replaced with specialized targets, e.g.
`//bin:ocamlc.byte`, `//bin:ocamlopt.byte`, etc. Targets are defined
for the standard "Big Four" compilers, profiling versions of same, and
flambda-enabled variants.

Build protocols & stacks:: Compiler build targets are implemented by
(possibly recursive) "build stacks", whose structure depends on the
link:bzl/docs/build_protocols.adoc[build protocol] in effect. For example, the build stack for build `ocamlc.byte` under the `std` protocol is:
+
    boot/ocamlc > ocamlc.byte
+
Under the `boot` protocol:
+
    boot/ocamlc > ocamlc.byte > ocamlc.byte
+
Different build protocols are used for different purposes (e.g.
testing v. deployment); defining them is not difficult, so if the
current configurations prove to be unsatisfactory they can be changed
relatively easily.

Archiveless builds:: Archive files (`.cma/.cmxa`) are for
distribution; for internal use they are unecesssary and wasteful.
Archiving of the libraries used in the (development) builds (i.e.
stdlib, ocamlcommon, etc.) is controlled by a boolean configuration
variable. By default it is false, so the libraries are not packaged
into archive files; this can be changed globally by passing a command-line
flag. See link:bzl/docs/libraries.adoc[libraries & archives] for more
information.

Nopervasives:: By default the build rules always use
`-nopervasives`. This requires that otherwise implicit dependencies
(`stdlib.cmx?a`, `std_exit.cm[o,x]`) be explicitly listed on the
command line, along with `-open stdlib`.  The rules do this automatically.

Fine-grained dependencies:: All dependencies are expressed as
dependencies on module, signature, or library dependencies. Libraries
are not archived by default, so a dependency on a library is
equivalent to (direct) dependencies on each of its dependencies. For
example, `asmcomp:Asmgen` depends on three `Stdlib` submodules. They,
rather than the (archived) library, are listed as dependencies. Along
with archiveless builds and `-nopervasives` , this means that changing
a `Stdlib` submodule will _not_ force a rebuild of a stdlib archive
and thus anything that depends on it. Only targets that depend
directly or indirectly on the changed code will be rebuilt.

Dependency types:: The Bazel rules also enforce a rudimentary type
discipline on dependencies. Signatures may only depend on signatures;
modules may depend on signatures, but such dependencies must be listed
in the `sig_deps` attribute.
+
Dependencies on `stdlib` submodules must be listed in attribute
`stdlib_deps`; others are listed in `deps`. For module rules (e.g.
`compiler_module`), only module dependencies are allowed in attributes
`deps` and `stdlib_deps`; modules that depend on signatures with no
corresponding structure file must list them separately in the
`sig_deps` attribute. For signature rules, by contrast (e.g.
`compiler_signature`), only signature dependencies are allowed.
+
This forces a separation between module and signature dependencies,
and allows Bazel to catch violations at analysis time.

CC Toolchain Integration:: The OCaml compilers are configured with
command strings they use to drive the C compiler, assembler, and
linker. The legacy system uses the `.configure` script to set these
strings. This introduces a risk, since there is no guarantee that the
C toolchain detected and used by `.configure` will be the one seen at
runtime -- what happens if the user has installed both GCC and Clang?
The Bazel code sets these configurations at build-time rather than
configure-time; it derives them from the selected Bazel toolchain.
This guarantees that the correct C toolchain will be used at runtime
(that is, when the compilers are run under Bazel's control). See
link:bzl/docs/ocaml_cc_config.adoc[ocamlcc config] for more info.

Testing support:: The legacy build system uses a custom test tool,
`ocamltest`, that orchestrates a variety of tasks that are usually
handled by a build system and/or testing framework. Under Bazel it is
not needed, so it is completely replaced by a few customized Bazel
test rules. The tests in `testsuite/tests` are completely under the
control of Bazel
+
WARNING: Only of a subset of the tests (174 of them, to be exact) have
been converted. See link:bzl/docs/testing.adoc[testing] for more
information.

Platform support:: Tested on MacOS and Linux (Ubuntu)

link:https://obazl.github.io/docs_obazl/[The OBazl Toolsuite] - outdated but still useful.


== Documentation

If you are not familiar with Bazel, never fear. The documentation
includes a lot of information about how Bazel works. But you should
start by reviewing the link:https://bazel.build/concepts/[Concepts]
section of the Bazel manual, and perhaps going through one of the
link:https://bazel.build/start/cpp[build tutorials].

CAUTION: these articles contain a lot of information but they are
drafts and in some cases are incomplete. You can find more additional
rough information in link:bzl/docs/notes[].

A good place to start is xref:bzl/docs/terminology.adoc[Terminology &
Symbols], followed by xref:bzl/docs/build_protocols.adoc[Build Protocols].

Articles:

* xref:bzl/docs/build_protocols.adoc[Build Protocols]
* xref:bzl/docs/build_targets.adoc[Build Targets]
* xref:bzl/docs/compilerlibs.adoc[Compiler-libs]
* xref:bzl/docs/cc_toolchain_integration.adoc[CC Toolchain Integration]
* xref:bzl/docs/configuration.adoc[Configuration]
* xref:bzl/docs/debugging.adoc[Debugging]
* xref:bzl/docs/diagnostics.adoc[Diagnostics]
* xref:bzl/docs/dynamics.adoc[Dynamics]
// * xref:bzl/docs/exceptions.adoc[Exceptions: warnings & errors]
* xref:bzl/docs/libraries.adoc[Libraries & Archives]
* xref:bzl/docs/macros.adoc[Macros]
* xref:bzl/docs/output_groups.adoc[Output Groups]
* xref:bzl/docs/performance.adoc[Performance]
* xref:bzl/docs/preprocessing.adoc[Preprocessing]
* xref:bzl/docs/primitives.adoc[Primitives]
* xref:bzl/docs/queries.adoc[Queries]
* xref:bzl/docs/repl.adoc[REPL]
* xref:bzl/docs/stdlib.adoc[Stdlib]
* xref:bzl/docs/terminology.adoc[Terminology & Symbols]
* xref:bzl/docs/testing.adoc[Testing]
* xref:bzl/docs/tools.adoc[Tools]
* xref:bzl/docs/tool_runners.adoc[Tool runners]
* xref:bzl/docs/verification.adoc[Verification]
// * xref:bzl/docs/windows.adoc[Windows]
* xref:bzl/docs/workflows.adoc[Workflows]

== Goals

The original goals were modest: just build the compilers, mostly. That
went so well that more ambitious goals are in order.

=== Compilers

Produce all compilers, in all variants:

* The Big Four: `ocamlc.byte`, `ocamlc.opt`, `ocamlopt.byte`, `ocamlopt.opt`.
* Flambda compilers: `ocamloptx.byte`, `ocamloptx.opt`, `ocamlc.optx`, `ocamlopt.optx`, `ocamloptx.otpx`.
* Profiling compilers: `ocamlcp.byte`, `ocamloptp.byte`, `ocamloptp.byte`, `ocamloptp.opt`
* Debug builds
* Instrumented builds

=== Fixed-point Bootstrapping

Ability to recursively build the endo-compilers (`ocamlc.byte`, ocamlopt.opt`) to reach a fixed point.

=== No hidden stuff

To the extend possible, everything in the build should be explicit. In
particular, `-nopervasives` is the default.

=== Complete, optimized configuration

Complete: support for all configuration settings supported by the legacy system

Optimized: the legacy system sets most configuration variables at
configure-time (when `./configure`` is run). A substantial portion of
those settings can and should be specifiable at build-time; they
involve data that can be derived by Bazel.

Configuration support is a Work-in-Progress; it's fairly complicated.
On the other hand, in general configuration management under Bazel is
very different (and much easier) than it is with configure/make. I
don't have detailed documentation yet, but you can find lots of notes
in link:bzl/docs[bzl/docs].

See xref:bzl/docs/configuration.adoc[Configuration] for more information.


=== Preprocessing: portability and optimization

The legacy build involves a certain amount of moderately complex
preprocessing, most of which depends on shell scripts/tools (sed, awk,
etc.) This is a portability problem; it just won't work on Windows,
and can be troublesome even in Unixworld.

The Bazel code has replaced most but not all of this by
link:https://mustache.github.io/mustache.5.html[mustache] template
processing. The engine used,
link:https://gitlab.com/jobol/mustach[mustach] (note the dropped `e`),
is written in portable C. It also uses
link:https://github.com/DaveGamble/cJSON[cJSON], a JSON library
written in portable C.

=== Ergonomics

It should be easy for developers to understand, use, and modify the Bazel system.

=== Efficiency

It should be at least as efficient _overall_ as the legacy system,
although for particular tasks the makefiles may be faster.

=== Alternate C Compilers

Support for
link:https://sr.ht/~motiejus/bazel-zig-cc/[Zig] and link:https://github.com/grailbio/bazel-toolchain[LLVM].

=== Cross-compiling

Bazel has excellent support for cross-compilation via link:https://bazel.build/extending/platforms[platforms] and link:https://bazel.build/extending/toolchains[toolchains]; for an overview see link:https://bazel.build/concepts/platforms[Building with platforms].

Goal: cross-compile non-cross-compilers. For example, to build, on an
x86 Mac, an arm Mac compiler, an x86 Linux compiler, an arm Linux compiler, etc.

Goal: cross-compile cross-compilers. For example, to build,
on an x86 Mac, a Linux x86 -> Linux arm OCaml compiler.

=== Mainainability

Eventually the code will be simplified and easy to read.

=== Persistent Workers

Bazel supports link:https://bazel.build/remote/persistent[persistent
workers] - tools that effectively run as service providers. Without
persistent workers, the compiler must startup, run, and shutdown once
for each file it compiles. With a persistent worker, the compiler
starts up once and stays loaded; clients then pass it source files to
compile.

Implementing OCaml compilers as persistent workers is really a
separate project, but I list it here as a general goal anyway.


== Non-Goals

NOTE: These are not _currently_ goals, but they could turn into goals.
  It depends on adoption. If nobody wants to use Bazel to develop the
  compilers and tools, then there would be no point in enhancing it.
  If you _do_ use it, and you need this stuff, please file an issue!

* CI builds

* Documentation builds.

* Editor/IDE integration

* OPAM support

* Windows support

* Distribution: packaging builds for distribution is not a current goal. No
point in supporting release builds unless and until the maintainers
decide they want to use Bazel in production. Such packaging logic is
generally not included in Bazel language rules, whose job is solely to
build things. Instead it is provided by separate rulesets such as:
+
** link:https://github.com/bazelbuild/rules_pkg[rules_pkg]
** link:https://github.com/vaticle/bazel-distribution[bazel-distribution]

== Status  (01/09/2023)

=== Legacy versions

==== branch: bazel/4.14.0

All the compilers and tools build. The bazel code on this branch is
very different from the latest version on `bazel/trunk`, and will not
be upgraded.

=== bazel/trunk, bazel/dev

The main branch of this repository is `bazel/trunk`; it tracks the
`trunk` branch of the upstream repository (and so may be outdated at
any given point in time).

The `bazel/dev` is where development happens.


==== Configuration

The Bazel build program supports command-line options to control:

* Platform-based toolchain selection. Sorry I don't have better docs
  on this - you'll have to root around in the sources and link:bzl/docs[] for more information
* Build subvariants - debug and instrumented builds are enabled via command-line flags
* Debugging profiles. Debugging configuration is rather involved,
  since the C runtimes and the OCaml tools can be debugged separately.
  Furthermore, there are two kinds of debugging: one involves building
  with `-g` and use of the debugger, and other (for C) involves
  setting preproccessor macros (typically `-DDEBUG`) whether or not
  `-g` is used. The Bazel build program affords fine-grained control
  of debug profiles - see link:bzl/docs/debugging.adoc[debugging] for details.
* Compile/link flags - by default, bootstrapping builds use flags like
  `-nostdlib`, `-use-prims`, `-principal`, etc. These are globally
  controllable. For example during development one might want to use
  `-no-principal`, or use a customize `primitives` file. These
  configurations can be set on the command line (or via `.bazelrc`).
  See link:bzl/docs/configuration.adoc[configuration] for more
  information.
* Build structure configuration. For lack of a better term. For
  example, configuration setting `--//config:sig_src` (subject to
  renaming) can be used to control whether or not `.mli` files are
  separately compiled, if the build targets are configured to use it.  For an example see target link:https://github.com/obazl-repository/ocaml/blob/1cef348aa2fd3536883169ad8b371d5c36870736/stdlib/BUILD.bazel#L2320-L2328[Stdlib.Weak].

==== Bootstrapping

The legacy makefile-based build defines multiple targets, one for each
of the Big Four compilers, and more for variants.

The original Bazel build had a single parameterized compiler target,
`//bin:ocamlcc`. Build variants were selected by passing arguments
controlling build and target platforms and some other build
parameters.

The current version is more like the makefile system, in that it has
distinct targets for each compiler (and also for each tool we have one
target for the vm version and one for the native version.) But these
targets are OCaml-ish: they are effectively interfaces on shared
implementation code.

See link:bzl/docs/build_protocols.adoc[build protocols] for more info.

==== Cross-builds

NOTE: 12/01/2022: Cross-compiling has not yet been adapted to use the new bootstrapping discipline.

Cross-compilation of the runtimes works: you can build a Linux x86_64
runtime on a MacOS x86_64 build host, for example. Cross-compilation
of the OCaml tools is currently limited to what can be produced by the
`vm>vm` bootstrap compiler, i.e. `ocamlopt.byte`, which runs on the VM
and emits native code. But support for variants of `ocamlopt.byte`
targeting different native platforms is not yet supported. Only the
variant targeting the local native platform is supported.

For more information see link:bzl/docs/cross_compilation.adoc[bzl/docs/cross_compilation.adoc]



