= OCaml: Proof-of-Concept OBazl Build

See the link:https://github.com/ocaml/ocaml[upstream repository] for the original OCaml README.

== Overview

OBazl is a Bazel Language Support Pack for OCaml. This fork of the
OCaml compiler toolset repository contains a Proof-of-Concept build
program written in OBazl. As a Proof-of-Concept whose primary purpose
is to demonsrate the capabilities of OBazl, it only builds a subset of
the targets supported by the Makefile-based production build program,
and it does not support the full range of configuration options.

It can build (bootstrap):

* compilers: `ocamlc`, `ocamlopt`
* tools: `ocamllex`, `ocamlyacc`, `ocamlobjinfo`, etc.

These targets can be built on Macos and Linux.

The OBazl ruleset used is a stripped-down, minimal version of the
standard ruleset called the `bootstrap` ruleset. It includes only the
functionality required to build the compiler. This means it contains
no direct support for PPX processing or for generalized namespaces,
for example. Furthermore, since the bootstrap ruleset is intended
solely for the purpose of bootstrapping the OCaml compilers and tools,
it is included in this repository (i.e. is not downloaded as an
external repository.)

More detailed documentation is in link:bzl/docs[bzl/docs].

Why use a minimal ruleset? Several reasons. Bootstrapping requires
some special support that is never needed for ordinary OCaml builds,
so we do not want to add that overhead to the standard ruleset. The
bootstrap ruleset is easy to understand and modify, so it serves as a
useful intro to the standard OBazl ruleset.

The build structure of the compilers is actually fairly
straightforward, in most places. It uses only one namespace (what Dune
calls a "wrapped" library), the Standard Library, whose resolver (or
"mapping") module is hand-coded. The bootstrapping process is a little
more complicated, but understandable. The most complicated part is
probably the preprocessing; but even the more complicated bits of
preprocessing are handled fairly easily by standard Bazel facilities.
It involves C interfacing. All of this makes this a useful starting
point for people interested in learning how to build OCaml software
using Obazl.


link:https://obazl.github.io/docs_obazl/[OBazl Version 1 documentation] - outdated but still useful.

link:https://github.com/obazl/rules_ocaml[obazl_rules_ocaml] - Branch obazl2



== Copyright

All files marked "Copyright INRIA" in this distribution are
Copyright (C) 1996-2021 Institut National de Recherche en Informatique et
en Automatique (INRIA) and distributed under the conditions stated in
file LICENSE.

