## WARNING: The legacy code conflates -g (build for debugger) and
## -DDEBUG, which may mean other things - here, it means the runtime
## must link instrtrace.c. Bazel makes a distinction: a `-c dbg` build
## adds `-g` but not `-DDEBUG`. A `-c fastbuild` build (the default)
## adds `-DDEBUG` but not `-g`. This makes sense considering DEBUG has
## no intrinsic relation to the debugger.

## The configure script puts both -O2 and -g in this var. For Bazel we
## have command line args to control optimizations. This function
## removes them from the OC_CFLAGS generated by ./configure.

def fix_oc_cflags(x):
    if "-O2" in x:
        x.remove("-O2")
    if "-g" in x:
        x.remove("-g")

    return x
