load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")

load(":BUILD.bzl", "progress_msg", "get_build_executor")

load("//bzl:providers.bzl",
     "BootInfo",
     "ModuleInfo",
     "SigInfo",
     "new_deps_aggregator",
     "OcamlSignatureProvider")

load("//bzl:functions.bzl",
     "get_module_name", "get_workdir", "tc_compiler")

load("//bzl/rules/common:options.bzl", "get_options")

load("//bzl/rules/common:impl_common.bzl", "dsorder")

load("//bzl/rules/common:DEPS.bzl", "aggregate_deps", "merge_depsets")

########################
def signature_impl(ctx, module_name):

    debug = False
    debug_bootstrap = False

    # if ctx.label.name in ["Pervasives"]
    #     debug = True

    # if "//toolchain/type:ocaml" in ctx.toolchains:
    #     fail("BOOT")

    basename = ctx.label.name
    from_name = basename[:1].capitalize() + basename[1:]

    # tc = ctx.exec_groups["boot"].toolchains["//toolchain/type:ocaml"]
    tc = ctx.toolchains["//toolchain/type:ocaml"]

    (target_executor, target_emitter,
     config_executor, config_emitter,
     workdir) = get_workdir(ctx, tc)

    #########################
    args = ctx.actions.args()

    executable = None
    if tc.dev:
        ocamlrun = None
        effective_compiler = tc.compiler
    else:
        ## tc.compiler runfiles: bottom element is always ocamlrun
        ocamlrun = tc_compiler(tc)[DefaultInfo].default_runfiles.files.to_list()[0]
        ## most recently built compiler:
        effective_compiler = tc_compiler(tc)[DefaultInfo].files_to_run.executable

    build_executor = get_build_executor(tc)
    print("xBX: %s" % build_executor)
    print("xTX: %s" % config_executor)
    print("xef: %s" % effective_compiler)

    if build_executor == "vm":
        executable = ocamlrun
        args.add(effective_compiler.path)
        if config_executor in ["sys"]:
            ext = ".cmx"
        else:
            ext = ".cmo"
    else:
        executable = effective_compiler
        ext = ".cmx"

    ################
    includes   = []

    sig_src = ctx.file.src
    if debug:
        print("sig_src: %s" % sig_src)

    # if sig_src.extension == "ml":
    #     # extract mli file from ml file

    # add prefix if namespaced. from_name == normalized module name
    # derived from sig_src; module_name == prefixed if ns else same as
    # from_name.

    ns = None
    # (from_name, ns, module_name) = get_module_name(ctx, sig_src)
    if debug:
        print("Module name: {src} To: {dst}".format(
            src = from_name, dst = module_name))

    # if False: ## ctx.attr.ppx:
    #     ## mlifile output is generated output of ppx processing
    #     mlifile = impl_ppx_transform("ocaml_signature", ctx,
    #                                  sig_src,
    #                                  module_name + ".mli")
    # else:

    if from_name == module_name:
        # if ctx.label.name == "CamlinternalFormatBasics_cmi":
        #     print("not namespaced")

        ## We need to ensure mli file and cmi file are in the same
        ## place. Since Bazel writes output files into its own dirs
        ## (won't write back into src dir), this means we need to
        ## symlink the source mli file into the same output directory,
        ## so that it will be found when it comes time to compile the
        ## .ml file.

        if debug:
            print("not namespaced")
        if sig_src.is_source:  # i.e. not generated by a preprocessor
            mlifile = ctx.actions.declare_file(workdir + module_name + ".mli") # sig_src.basename)
            ctx.actions.symlink(output = mlifile,
                                target_file = sig_src)
            if debug:
                print("symlinked {src} => {dst}".format(
                    src = sig_src.path, dst = mlifile.path))
        else:
            ## generated file, already in bazel dir
            if debug:
                print("not symlinking {src}".format(
                    src = sig_src))

            mlifile = sig_src

    else:
        # namespaced w/o ppx: symlink sig_src to prefixed name, so
        # that output dir will contain both renamed input mli and
        # output cmi.
        ns_sig_src = module_name + ".mli"
        if debug:
            print("ns_sig_src: %s" % ns_sig_src)
        mlifile = ctx.actions.declare_file(workdir + ns_sig_src)
        ctx.actions.symlink(output = mlifile,
                            target_file = sig_src)
        if debug:
            print("mlifile %s" % mlifile)

    direct_inputs = [mlifile]

    # if sig_src.extension == "ml":  ## wtf?
    #     ofile = workdir + sig_src.basename + "i"
    #     out_cmi = ctx.actions.declare_file(ofile)
    # else:
    ocmi = workdir + module_name + ".cmi"
    # if ctx.label.name == "CamlinternalFormatBasics_cmi":
    #     print("OCMI: %s" % ocmi)

    action_outputs = []
    out_cmi = ctx.actions.declare_file(ocmi)
    action_outputs.append(out_cmi)

    _options = get_options(ctx.attr._rule, ctx)
    if ( ("-bin-annot" in _options)
         or ("-bin-annot" in tc.copts) ):
        out_cmti = ctx.actions.declare_file(workdir + module_name + ".cmti")
        action_outputs.append(out_cmti)
        # default_outputs.append(out_cmt)
    else:
        out_cmt = None

    if debug:
        print("out_cmi %s" % out_cmi)


    ################################################################
    ################  DEPS  ################
    depsets = new_deps_aggregator()

    # if ctx.attr._manifest[BuildSettingInfo].value:
    #     manifest = ctx.attr._manifest[BuildSettingInfo].value
    # else:
    manifest = []

    # if ctx.label.name == "Stdlib_cmi":
    #     print("Stdlib manifest: %s" % manifest)
        # fail("X")

    for dep in ctx.attr.deps:
        depsets = aggregate_deps(ctx, dep, depsets, manifest)

    if hasattr(ctx.attr, "ns"):
        if ctx.attr.ns:
            # for dep in ctx.attr.ns:
            depsets = aggregate_deps(ctx, ctx.attr.ns, depsets, manifest)

    ## build depsets here, use for OcamlProvider and OutputGroupInfo
    sigs_depset = depset(
        order=dsorder,
        direct = [out_cmi],
        transitive = [merge_depsets(depsets, "sigs")])

    cli_link_deps_depset = depset(
        order = dsorder,
        transitive = [merge_depsets(depsets, "cli_link_deps")]
    )

    afiles_depset  = depset(
        order=dsorder,
        transitive = [merge_depsets(depsets, "afiles")]
    )

    ofiles_depset  = depset(
        order=dsorder,
        transitive = [merge_depsets(depsets, "ofiles")]
    )

    archived_cmx_depset = depset(
        order=dsorder,
        transitive = [merge_depsets(depsets, "archived_cmx")]
    )

    paths_depset  = depset(
        order = dsorder,
        direct = [out_cmi.dirname],
        transitive = [merge_depsets(depsets, "paths")]
    )

    # if ctx.label.name == "CamlinternalFormatBasics_cmi":
    #     print("depsets: %s" % depsets)
    #     fail("x")

    if debug:
        print("tgt: %s" % ctx.label)
        print("target_executor: %s" % target_executor)
        print("target_emitter: %s" % target_emitter)
        print("config_executor: %s" % config_executor)
        print("config_emitter: %s" % config_emitter)
        print("ocamlrun: %s" % ocamlrun)
        print("effective_compiler: %s" % effective_compiler)
        print("executable: %s" % executable)
        print("tc.dev: %s" % tc.dev)
        # if ctx.label.name == "CamlinternalFormatBasics_cmi":
        #     fail()

    resolver = []
    if hasattr(ctx.attr, "ns"):
        if ctx.attr.ns:
            resolver.append(ctx.attr.ns[ModuleInfo].sig)
            resolver.append(ctx.attr.ns[ModuleInfo].struct)
            ns = ctx.attr.ns[ModuleInfo].struct.basename[:-4]
            args.add_all(["-open", ns])

    if hasattr(ctx.attr, "_opts"):
        args.add_all(ctx.attr._opts)

    if not ctx.attr.nocopts:
        args.add_all(tc.copts)

    args.add_all(tc.warnings[BuildSettingInfo].value)

    for w in ctx.attr.warnings:
        args.add_all(["-w",
                      w if w.startswith("-")
                      else "-" + w])

    for dep in ctx.attr.deps:
        if hasattr(ctx.attr, "stdlib_primitives"): # test rules
            if dep.label.package == "stdlib":
                if "-nopervasives" in _options:
                    _options.remove("-nopervasives")
    args.add_all(_options)

    if hasattr(ctx.attr, "ns"):
        if ctx.attr.ns:
            # includes.append(ctx.attr.ns[ModuleInfo].sig.dirname)
            includes.append(ctx.attr.ns[ModuleInfo].sig.dirname)
            direct_inputs.append(ctx.attr.ns[ModuleInfo].sig)
            direct_inputs.append(ctx.attr.ns[ModuleInfo].struct)


    if hasattr(ctx.attr, "stdlib_primitives"): # test rules
        if ctx.attr.stdlib_primitives:
            includes.append(ctx.attr._stdlib[ModuleInfo].sig.dirname)
            direct_inputs.append(ctx.attr._stdlib[ModuleInfo].sig)
            direct_inputs.append(ctx.attr._stdlib[ModuleInfo].struct)

    ccInfo_list = []

    # nsns_depset = []
    # if hasattr(ctx.attr, "ns"):
    #     # print("HAS ctx.attr.ns")
    #     ## Only -open Stdlib if we have a dep on Stdlib.
    #     if ctx.files.deps :
    #         if ctx.attr.ns:
    #             # if BootInfo in ctx.attr.ns:
    #                 # nsns_depset = [ctx.attr.ns[BootInfo].inputs]

    #             # for f in ctx.attr.ns[DefaultInfo].files.to_list():
    #             #     # args.add("-I", f.dirname)
    #             #     includes.append(f.dirname)
    #                 # args.add(f)

    #             args.add("-no-alias-deps")
    #             args.add("-open", ns)
        #     else:
        #         args.add("-nopervasives")
        # else:
        #     args.add("-nopervasives")

    # if ctx.label.name == "Stdlib_cmi":
    #     print("sig depset : %s" % depsets)
        # fail("x")

    # arch_depset = merge_depsets(depsets, "archives")
    # for arch in arch_depset.to_list():
    #     includes.append(arch.dirname)

    # args.add_all(paths_depset.to_list(), before_each="-I")
    includes.extend(paths_depset.to_list())

    args.add_all(includes, before_each="-I", uniquify = True)

    if sig_src.extension == "ml":
        args.add("-i")
    else:
        args.add("-c")

    args.add("-o", out_cmi)

    pack_ns = False
    if hasattr(ctx.attr, "_pack_ns"):
        if ctx.attr._pack_ns:
            if ctx.attr._pack_ns[BuildSettingInfo].value:
                pack_ns = ctx.attr._pack_ns[BuildSettingInfo].value
                # print("GOT PACK NS: %s" % pack_ns)
    if pack_ns:
        args.add("-for-pack", pack_ns)

    args.add("-intf", mlifile)

    if ctx.files.data:
        direct_inputs.extend(ctx.files.data)

    inputs_depset = depset(
        order = dsorder,
        direct = []
        + direct_inputs # + ctx.files._ns_resolver,
        # + [tc.compiler[DefaultInfo].files_to_run.executable],
        # + ctx.files.data if ctx.files.data else [],
        + [effective_compiler]
        + resolver
        ,
        transitive = []## indirect_inputs_depsets
        + [merge_depsets(depsets, "sigs"),
           merge_depsets(depsets, "cli_link_deps")
           ]
        # + depsets.deps.structs
        # + depsets.deps.sigs
        # + depsets.deps.archives
        # + ns_resolver_depset
        # + [tc.compiler[DefaultInfo].default_runfiles.files]
    )

    ##########################################
    ################  ACTION  ################
    ctx.actions.run(
        executable = executable,
        arguments = [args],
        inputs = inputs_depset,
        outputs = action_outputs,
        tools = [
            # tc_compiler(tc)[DefaultInfo].default_runfiles.files,
            # tc_compiler(tc)[DefaultInfo].files_to_run
        ],
        mnemonic = "CompileOcamlSignature",
        progress_message = progress_msg(workdir, ctx)
    )

    #############################################
    ################  PROVIDERS  ################

    default_depset = depset(
        order = dsorder, direct = [out_cmi]
    )

    defaultInfo = DefaultInfo(
        files = default_depset
    )

    ## FIXME: switch to SigInfo provider
    sigProvider = OcamlSignatureProvider(
        mli  = mlifile,
        cmi  = out_cmi,
        cmti = out_cmti
    )

    sigInfo = SigInfo(
        mli  = mlifile,
        cmi  = out_cmi,
        cmti = out_cmti
    )

    bootInfo = BootInfo(
        sigs     = sigs_depset,
        cli_link_deps = cli_link_deps_depset,
        afiles   = afiles_depset,
        ofiles   = ofiles_depset,
        archived_cmx  = archived_cmx_depset,
        paths    = paths_depset,

        # ofiles   = ofiles_depset,
        # archives = archives_depset,
        # astructs = astructs_depset,
    )

    providers = [
        defaultInfo,
        bootInfo,
        sigProvider,
        sigInfo
    ]

    if ccInfo_list:
        providers.append(
            cc_common.merge_cc_infos(cc_infos = ccInfo_list)
        )

    return providers
