w = struct(
    AMBIGUOUS_NAME_41 = "41",
    DISAMBIGUATED_NAME_42 = "42",
    OPEN_SHADOW_IDENTIFIER_44 = "44",
    FRAGILE_MATCH_4 = "4",
    MISSING_RECORD_FIELD_PATTERN_9 = "9",
    MISSING_MLI = "70",
    MODULE_LINKED_TWICE = "31",
    NAME_OUT_OF_SCOPE = "40",
    NO_CMI_FIE  = "49",
    UNUSED_VALUE_DECLARATION_32 = "32",
)

