= bootstrapping the compilers

The OCaml compiler collection may be defined inductively in a form
that is homomorphic (or at least analogous) to the inductive
definition of the natural numers.

== Boot stack

[cols="^1,^1,2,10"]
|===
| Nat | ^| OCamlCC | Remarks

| Z | 0 | `boot/ocamlc` | precompiled

| SZ | 1 | `_boot/ocamlc.byte` | built by `boot/ocamlc`

| SSZ | 2 | `_boot/ocamlopt.byte` | built by `boot/ocamlc`

| SSSZ | 3 | `_boot/ocamlopt.opt` | built by `ocamlopt.byte`

| SSSSZ | 4 | `_boot/ocamlc.opt` | built by `ocamlopt.byte`

|===

Remarks: the VM compilers (`ocamlc.byte`, `ocamlopt.byte`) built in
the boot stack are built from source by the precompiled boot
compiler, so they are not fully "new". The native compilers
(`ocamlopt.opt`, `oqcamlc.opt`) similarly are built from source by the
`ocamlopt.byte` compiler built by the boot compiler.


== Fixed-point stack

[cols="^1,^1,2,10"]
|===
| Nat | ^| OCamlCC | Remarks

| Z | 0 | `boot/ocamlc` | precompiled

| SZ | 1 | `_baseline/ocamlc.byte` | built by `boot/ocamlc`

| SSZ | 2 | `_fp/ocamlc.byte` | built by `_baseline/ocamlc.byte`

| SSSZ | 3 | `_fp/ocamlopt.byte` | built by `_fp/ocamlc.byte`

| SSSSZ | 4 | `_baseline/ocamlopt.opt` | built by `_fp/ocamlopt.byte`

| SSSSSZ | 5 | `_fp/ocamlopt.opt` | built by `_baseline/ocamlopt.opt`

| SSSSSSZ | 6 | `_fp/ocamlc.opt` | built by `_baseline/ocamlopt.opt`

|===



== Implemention details

[cols="^1,^1,2,2,10"]
|===
| Nat | ^| Compiler ^| Lexer | Config

| Z | 0 | ocamlc.boot | ocamllex.boot
| `//'config/target/executor:boot` +
`//'config/target/emitter:boot` +
`//toolchain:compiler` = `//boot:ocamlc.boot` +
`//toolchain:lexer`      = `//boot:ocamllex.boot` +
`//toolchain:runtime` = `//runtime:camlrun`

| SZ | 1 | ocamlc.baseline | ocamllex.boot
| `//'config/target/executor:baseline` +
`//'config/target/emitter:baseline` +
`//toolchain:compiler` = `//boot:ocamlc.boot` +
`//toolchain:lexer`       = `//boot:ocamllex.boot` +
`//toolchain:runtime` = `//runtime:camlrun`

| SSZ | 2 | ocamlc.byte | ocamllex.byte
| `//'config/target/executor:vm` +
`//'config/target/emitter:vm` +
`//toolchain:compiler` = `//bin:ocamlcc` +
`//toolchain:lexer` = `//bin:ocamllex` +
`//toolchain:runtime` = `//runtime:camlrun`

| SSSZ | 3 | ocamlopt.byte |
| `//'config/target/executor:vm` +
`//'config/target/emitter:sys` +
`//toolchain:compiler` = `//bin:ocamlcc` +
`//toolchain:lexer` = `//bin:ocamllex` +
`//toolchain:runtime` = `//runtime:asmrun`

| SSSSZ | 4 | ocamlopt.opt | ocamllex.opt
| `//'config/target/executor:sys` +
`//'config/target/emitter:sys` +
`//toolchain:compiler` = `//bin:ocamlcc` +
`//toolchain:lexer` = `//bin:ocamllex` +
`//toolchain:runtime` = `//runtime:asmrun`

| SSSSSZ | 5 | ocamlc.opt |
| `//'config/target/executor:sys` +
`//'config/target/emitter:vm` +
`//toolchain:compiler` = `//bin:ocamlcc` +
`//toolchain:lexer` = `//bin:ocamllex` +
`//toolchain:runtime` = `//runtime:camlrun`

|===



Without transitions, circularity. Note the same config id on all targets:

----
.-> //bin:ocamlcc (3b3d2b2d012caaeea2d4fcbb07cc99215977da019d5bb230ada48e31aecfc892)
|   //toolchain/adapter:boot (3b3d2b2d012caaeea2d4fcbb07cc99215977da019d5bb230ada48e31aecfc892)
|   //toolchain:compiler (3b3d2b2d012caaeea2d4fcbb07cc99215977da019d5bb230ada48e31aecfc892)
`-- //bin:ocamlcc (3b3d2b2d012caaeea2d4fcbb07cc99215977da019d5bb230ada48e31aecfc892)
----
