= Build Protocols
:toc: auto
:toclevels: 3


== Overview: build protocols and stacks

A _build protocol_ is not much more than a dependency structure. The
compiler build rules are quasi-recursive: each depends on a toolchain
that references (and thus depends on) a compiler. That compiler target
in turn depends on a toolchain, which depends on a compile, and so on;
the chain bottoms out at the precompiled `boot/ocamlc` compiler.

Compiler dependencies are controlled by a configuration setting,
`//config/build/protocol`, and _transition functions_ that may change
the protocol. The result is each compiler is the end result of a _build stack_; for
example, the minimal build stack required to build `ocamlc.opt` is:

    boot/ocamlc > ocamlopt.byte > ocamlc.opt

Each build protocol configures the build stack in a different way. For
example, the `boot` protocol inserts "bootstrapping" (i.e.
self-compiling) steps, in order to bring the compilers into alignment
with the baseline source code. It uses the following build stack to produce `ocamlc.byte`:

    boot/ocamlc > ocamlc.byte > ocamlc.byte


WARNING: The build protocols used by the various targets have not been
thoroughly audited (this is still work-in-process), so they may not be
optimal. E.g. a target might use a bootstrapping (recursive) build
step where it does not need too.  Please file an issue if you find problems.

== The Standard Protocol

Package:  `//bin`

Compiler targets in the `//bin` package are built directly from
`/boot/ocamlc`. The standard protocol does not bootstrap to
reach a fixed point, on the assumption that `boot/camlc` and the
sources are already there.

CAUTION: The standard protocol is only appropriate for release
commits, where the source code matches `boot/ocamlc`. This would be
the case where the user just wants to build the compilers from a
source release for use in a project.

=== Standard build stacks

* `//bin:ocamlc.byte`: `boot/ocamlc > ocamlc.byte`
* `//bin:ocamlopt.byte`: `boot/ocamlc > ocamlopt.byte`
* `//bin:ocamlopt.opt`: `boot/ocamlc > ocamlopt.byte > ocamlopt.opt`
* `//bin:ocamlc.opt`: `boot/ocamlc > ocamlopt.byte > ocamlc.opt`


== The Boot Protocol

Package: `//boot`. Not intended for direct use; used only by the
`//boot:checkpoint` target.

The `//boot:checkpoint` run target builds the compilers using
 `boot/camlc`, just like the standard protocol, but it adds some
 bootstrapping steps in order to bring the built compilers into
 alignment with the baseline source code. It copies the built images
 to `.baseline` and exposes them in workspace `@dev`. They are
 used for compiler development.

=== Boot build stacks

[cols="1,2"]
|===
| Installed | Build stack
| `@dev//bin:ocamlc.byte` | `(boot/ocamlc > ocamlc.byte) > ocamlc.byte`
| `@dev//bin:ocamlopt.byte` | `(boot/ocamlc > ocamlc.byte) > ocamlopt.byte`
| `@dev//bin:ocamlopt.opt` | `(boot/ocamlc > ocamlc.byte > ocamlopt.byte) > ocamlopt.opt`
| `@dev//bin:ocamlc.opt` | `(boot/ocamlc > ocamlc.byte >ocamlopt.byte > ocamlopt.opt) > ocamlc.opt`
|===

The same protocol is used to build the profiliing compilers
(`@dev//bin:ocamlcp.byte`, etc.) and the flambda compilers
(`@dev//ocamlc.optx`, etc.)


== The Test Protocol (for development)

Package:  `//test`

These builds use the baseline compilers built by running
`//boot:checkpoint` to build new versions of the compilers,
incorporating any changes in the source code. This is just an
optimization; it uses the fastest compilers and avoids the lengthier
build stacks that would be required by the `std` protocol.

[cols="1,2"]
|===
| *target* | *build stack*
| `//test:ocamlc.byte` | `@dev//bin/ocamlc.opt > ocamlc.byte`
| `//test:ocamlopt.byte` | `@dev//bin/ocamlc.opt > ocamlopt.byte`
| `//test:ocamlopt.opt` | `@dev//bin/ocamlopt.opt > ocamlopt.opt`
| `//test:ocamlc.opt` | `@dev//bin/ocamlopt.opt > ocamlc.opt`
|===

Targets in the testsuite depend on the `//test` compilers so they are
built under the test protocol.  See article link:testing.adoc[testing] for more information.


== The Fastbuild Protocol

By default, targets in `//tools` are built under the standard
protocol; this allows them to be built even if `bazel run
boot:checkpoint` as not been run. If it has been run, the tools can be
built under the _fastbuild_ protocol, using the baseline compilers.
For example:

    bazel run tools:ocamldep.byte --//config/build/protocol=fb
    bazel run tools:ocamldep.opt  --//config/build/protocol=fb

== The Sys Test Protocol

CAUTION: Not yet implemented

Once you've made and tested your changes using the baseline compilers,
it's time to run a system test. This bootstraps all the compilers to a
fixed point, starting from `boot/ocamlc` and then runs the entire
testsuite.

== The Reboot Protocol

CAUTION: Not yet implemented

Once you've run the system test, so you're confident your shiny new
compiler is copacetic, you run the reboot protocol. It bootstraps
`ocamlc.byte` repeatedly until it reaches a fixed point and then
copies it to the `boot` directory, replacing `boot/ocamlc`.
implemented]

== The Deployment Protocol

CAUTION: Not yet implemented

The protocol for building and packaging the compilers and tools for
distribution is distinct from the protocols for building the
compilers.
