= configuration

The `./configure` script emits several classes of config data: toolchain and system.

* toolchain config is stuff like compile and link flags. determined by finding and interrogating the tools.

* system config is stuff like OS, architecture. determined by interrogating the system in various ways

* installation config: e.g. the standard PREFIX, EXEC_PREFIX, etc. specified by the user via `./configure` arguments and/or environment vars.

OBazl partitions the output of `./configure` accordingly:

* `//toolchain/profile/cc` and its subdirectories contain toolchain configuration data
* `//profile/system` contains system configuration data; for example
  `//profile/system/local` for the local system, and, for
  cross-compilation, `//profile/system/linux` and
  `//profile/system/macos`.

The configuration information is communicated to build rules through
Bazels _custom variable_ mechanism.

=== config settings


* `--//config:primitives=/path/to/primitives` - sets the file of
  primitives to be used with `-use-primitives. This is a global
  setting. Default is `//runtime:primitives`.

NB: example of file that needs this is asmcomp/reloadgen.ml. Compiled


* `--//config:sig_src` (boolean) may be used by `compiler_module` rules to
  select, for the `sig` attribute, a source .mli file instead of a the
  label of a compiled .cmi. (I.e whether or not .mli files are
  compiled separately.)

* `--config:principal` (boolean) may be used by rules to decide
  whether to pass the `-principal` flag.

* `--//config:bin-annot` (boolean, default true). Pass
  `--//config:bin-annot=False` to disable.

* `--//config:absname` (boolean)

* `--//config:warnings (string list) - use to override the default
  `["-w", "+a-4-9-41-42-44-45-48"]`


== C config

C compile flags for specific files may be set on the command line using `--per_file_copt`.
