= Configuration
:toc: auto
:toclevels: 4

Configuration is a Work-In-Progress. The following <<Notes>> may
help, but see also link:notes/config[]


== Config groups

See link:https://bazel.build/run/bazelrc#config[--config] and xref:../../.bazelrc[.bazelrc].

== Summary

CAUTION: WIP.

=== Command-line options

Two ways to set a boolean option to true

   --//config/ocaml/compile:bin-annot
   --//config/ocaml/compile:bin-annot=True

Two ways to set a boolean option to false

   --no//config/ocaml/compile:bin-annot
   --//config/ocaml/compile:bin-annot=False

=== Toolchain Configurations

[cols="3,1,5"]
|===
| Setting | Default | Remarks
| `//toolchain:compiler` | | Controls the compiler used by build
  targets. Usually set by top-level build targets (e.g. compiler and
  tool targets), and should not be set by user. See
  xref:build_protocols.adoc[Build Protocols] for more information.
|===

=== Action Configurations

Action configurations control build actions. As opposed to "build
configurations" (like enabling flambda) that control the structure of
the build outputs.

==== OCaml Compilation

[cols="3,1,5"]
|===
| Setting | Default | Remarks
| `//config/ocaml/compile:absname` | True | Inserts `-absname` to all compile targets
| `//config/ocaml/compile:bin-annot` | False | Inserts `-bin-annot` to all compile targets
| `//config/ocaml/compile:principal` | True | Inserts `-principal` to all compile targets
|===

Remarks:

* "All compile targets": all `*_module` and `*_signature` rule targets


===== Diagnostics

See xref:diagnostics.adoc[Diagnostics] for more information and guidance.

[cols="3,1,5"]
.OCaml diagnostics
|===
| Setting | Default | Remarks
| `//config/ocaml/archive:verbose`  | False | Inserts `-verbose` for all OCaml archiving actions, telling the compiler to print the commands it uses to drive the C toolchain (archiver).
| `//config/ocaml/compile:verbose` | False | Inserts `-verbose` to all OCaml compile actions, telling the compiler to print the commands it uses to drive the C toolchain (assembler, compiler).
| `//config/ocaml/link:verbose` | False | Inserts `-verbose` for all OCaml link actions, telling the compiler to print the commands it uses to drive the C toolchain (linker).
| `//config/ocaml/warnings:report`  | False | If True, warnings are passed with '+' so the compiler will write warning messages to stderr; otherwise they are passed with '-' (ignored).
|===

[cols="3,1,5"]
.OCaml/cc diagnostics
|===
| Setting | Default | Remarks
| //config/cc:verbose  | | obsolete?
| //config/ocaml/cc/archive:verbose  | False | passes verbose flag to archiver when native OCaml compile
r invokes it to create an OCaml archive file.
| //config/ocaml/cc/asm:keep  | False | passes `-S`, to retain assembler source when native compiler compiles a module
| //config/ocaml/cc/asm:verbose  | False | passes verbose flag to assembler when native OCaml compiler invokes it to compile a module.
| //config/ocaml/cc/link:verbose  | |
| //config/ocaml/cc/compile:verbose  | False | passes verbose flag to C compiler
|===

Abbreviations (defined in `.bazelrc`):

* `--config=ccv` - 


==== OCaml Linking

[cols="3,1,5"]
|===
| Setting | Default | Remarks
|===

==== OCaml Archiving

[cols="3,1,5"]
|===
| Setting | Default | Remarks
|===

=== Build Configurations

==== Compilers

[cols="3,1,5"]
|===
| Setting | Default | Remarks
| //config/cmm/invariants:enabled  | |
| //config/cmm/logging:enabled  | |
| //config/ocaml/cmm/invariants:enabled  | |
| //config/ocaml:with_cmm_invariants  | |
| //config/ocaml:flat_float_array  | |
| `//config/ocaml/compiler/libs:archived`  | False | Determines whether or not libraries are archived.
|===

==== Flambda

[cols="3,1,5"]
|===
| //config/flambda/invariants:enabled  | |
| //config/flambda/logging/raw:enabled  | |
| //config/flambda/logging:enabled  | |
| //config/flambda:verbose  | |
| //config/ocaml/flambda/invariants:enabled  | |
| //config/ocaml/flambda:enabled  | |
|===

==== Runtimes

[cols="3,1,5"]
|===
| Setting | Default | Remarks
| //runtime:DEBUG | |
| //runtime:INSTRUCTION_TRACE | |
| //runtime:INSTRUMENT | |
| //config:instrumented | |
| //runtime:args | |
| //runtime:fastbuild | |
| //runtime:runtime | |
| //runtime:trace | |
| //runtime:primitives | |
| //runtime:use_prims | |
|===

Obsolete:

* //config/variant:instrumented


=== Diagnostics

Verbosity, logging, etc.

[cols="3,1,5"]
|===
| Setting | Default | Remarks
|===

=== Optimizations (o11n)

[cols="3,1,5"]
|===
| Setting | Default | Remarks
| //config/ocaml/cc/compile/o11n/level:level  | |
| //config/ocaml/o11n/xmo:enabled  | |
|===


=== CC configuration

[cols="3,1,5"]
|===
| Setting | Default | Remarks
| //config/cc:function-sections  | |
|===


=== Misc

[cols="3,1,5"]
|===
| Setting | Default | Remarks
| //config/mode:pedantic  | |
| //config/ocaml:camlheaders  | |
| //config/ocaml:sig_src | |
| //config/pack:dynlink | |
| //config/pack:ns | |
| //config/target/emitter:emitter | |
| //config/target/executor:executor | |
| //config/toolchain:toolchain | |
| //config/tools:verbose | |
| //config:debug | |
| //config:manifest | |
| //config:sig_src | |
| //config:target_host | |
| //config:verbose | |
| //config:warnings | |
| //platform/xtarget:xtarget | |
| //test:verbose | |
| //testsuite/tests:with-stdlib | |
| //toolchain/targetX/executor:executor | |
| //toolchain:compiler | |
| //tools:verbose | |
| //:arg | |
| //:verbose | |
| //bin:verbose | |
| //boot:verbose | |
|===

Obsolete:

* //config/variant:pedantic

== Open Issues

* Which options are appropriate to which build actions?  Some are only appropriate to compilation, some only to linking, etc.
  ** `-absname` - relevant to all build actions or just compilation?
  ** `-principal` - compile only?

== Notes

[IMPORTANT]
====
The general idea is something like the following

* Partition configuration settings into categories: system config,
(compiler) build config (e.g. `flat_float_array`,
`with_cmm_invariants`), deployment config (install directories,
mostly), etc. See link:notes/config/census.adoc[config census].

* Put all the config rules and logic in one place: `//config`

* Generate `config.ml` from a mustache template file and a json data file

* Before generating `config.ml`, use a Bazel rule to update the json
  data file with data derived from the selected CC toolchain
====


Two broad classes:

* fixed - forced by platform (e.g. endianness, word size)
* preferential - user's choice

Several sub-classes:

* system config (fixed)
* toolchain config (fixed once toolchain is selected)
* build config (preferential - how the user wants the compilers to be configured)
* deployment config (preferential) - how the user wants stuff installed

And more:

* cc build toolchain config - for the cc toolchain used to build the compilers
* ocaml_cc tc config - the config used by OCaml when it uses the cc tc to compile, assemble, or link (e.g. mkexe etc.)
* ocaml toolchain config (= build config?)

The `./configure` script emits several classes of config data: toolchain and system.

* toolchain config is stuff like compile and link flags. determined by finding and interrogating the tools.

* system config is stuff like OS, architecture. determined by interrogating the system in various ways

* installation config: e.g. the standard PREFIX, EXEC_PREFIX, etc. specified by the user via `./configure` arguments and/or environment vars.

The Bazel code partitions the output of `./configure` accordingly:

WARNING: outdated. Most of the config stuff is now in link:/config[//config]

* `//toolchain/profile/cc` and its subdirectories contain toolchain configuration data
* `//profile/system` contains system configuration data; for example
  `//profile/system/local` for the local system, and, for
  cross-compilation, `//profile/system/linux` and
  `//profile/system/macos`.

The configuration information is communicated to build rules through
Bazels _custom variable_ mechanism.

=== config settings


* `--//runtime:primitives=/path/to/primitives` - sets the file of
  primitives to be used with `-use-primitives. This is a global
  setting. Default is `//runtime:primitives.dat`.

NB: example of file that needs this is asmcomp/reloadgen.ml. Compiled


* `--//config:sig_src` (boolean) may be used by `compiler_module` rules to
  select, for the `sig` attribute, a source .mli file instead of a the
  label of a compiled .cmi. (I.e whether or not .mli files are
  compiled separately.)

* `--config:principal` (boolean) may be used by rules to decide
  whether to pass the `-principal` flag.

* `--//config:bin-annot` (boolean, default true). Pass
  `--//config:bin-annot=False` to disable.

* `--//config:absname` (boolean)

* `--//config:warnings (string list) - use to override the default
  `["-w", "+a-4-9-41-42-44-45-48"]`


=== features



==== -D_FILE_OFFSET_BITS=64

Not needed on 64 bit platforms.

"This macro should only be selected if the system provides mechanisms
for handling large files. On 64 bit systems this macro has no effect
since the *64 functions are identical to the normal functions."

link:https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html[Feature test macros]

==== -use-prims

WARNING: This option is disabled in the current code. The legacy
makefiles use it almost everywhere, but it is only needed in specific
places under special circumstances (i.e. you are making changes to the
C primitives). So I've just omitted it until I can work out the proper
way to support it. (The code to make it work is there, just disabled).

==== function_sections

"Function sections" is a technique for reducing the size of the kernel image."  By eliminating dead code, apparently.

(link:https://elinux.org/Function_sections[Function sections] elinux.org)

link:https://www.vidarholen.net/contents/blog/?p=729[So what exactly is -ffunction-sections and how does it reduce binary size?]

But: "When you specify these options, the assembler and linker will create larger object and executable files and will also be slower."

link:https://gcc.gnu.org/onlinedocs/gcc-2.95.2/gcc_2.html#SEC10[Options that Control Optimization]


==== data sections

link:https://devzone.nordicsemi.com/f/nordic-q-a/48438/what-is--fdata-sections-in-gcc[What is -fdata-sections in gcc?]

==== misc

Thin archives, --start-lib, --end-lib: link:https://maskray.me/blog/2022-01-16-archives-and-start-lib[Archives and --start-lib]

=== C config

C compile flags for specific files may be set on the command line using `--per_file_copt`.


=== new regime

Distinct classes of config data.

Features: ?

* system config - produced by system interrogtion (./configure) -
+
For example, a C header with #define macros like HAVE_UNISTD_H. OCaml
uses `runtime/caml/s.h` for these C config items.

+
* toolchain config - cflags, extensions, etc. Under Bazel these are
  handled by the toolchain, and config settings; should not be
  in ./configure.

* build config - e.g. flambda enable, force_instrumented_runtime,
  flat_float_array, etc. Also stuff like `--enable-mmap-map-stack`,
  `--disable-stdlib-manpages`, etc..
+
** These config items determined by user, not system interrogation - should not be in ./configure.
** OTOH, whether such a feature may be platform- or toolchain-dependent, e.g. function-sections.
+
* deployment config - e.g. libdir

Problem: some config items controlled by the user via Bazel build
settings must be communicated to the OCaml source files.  For
example, `asmcomp/asmlink.ml` makes decisions based on the
`function_sections` config item.

Problem: some config items span two (or more?) categories.For example,
`-ffunction-sections` is a user-controllable item, specifiable via
something like `--//config/link:function_sections`. OTOH, not all
toolchains support it, so system interrogation must discover that.


Problem: we actually have two sets of config items. First we have
those that control the build of the compiler. Then we have those that
the compiler supports, i.e.those that configure a built compiler's
operations. To continue the example, we can build the compiler with
(or without) `-ffunction-sections`; users of the built compiler can
tell it to emit code with or without `-ffunction-sections`.



Configuration involves:

* Auto-detected feature options set by `./configure` by interrogating
  the system. This usually results in setting `#define` macros or `-D`
  build flags in source files or headers; e.g.
+
    #define HAS_MACH_ABSOLUTE_TIME 1      #  in runtime/caml/s.h
    let ocamlc_cppflags = "-D_FILE_OFFSET_BITS=64 "  # in utils/config_ml.generated
+
* User-controllable configuration options exposed by `./configure`, e.g.
+
    --disable-debug-runtime
+
* User-controllable build options - arguments or env variables passed
  to `make`; e.g. `CC`, `CFLAGS`, etc. Many such make/compiler/linker
  variables are set to default values by `./configure`.

The OBazl rules always set such configuration items to default values.

