= Building OCaml with OBazl

== bootstrapping

We build bytecode compiler and tools only, Ignoring flexdll and docs.
Targets generate `.depends` are also ignored; all dependencies are
explicitly enumerated in the BUILD.bazel files.

=== make world

.root Makefile
```
world: coldstart
	$(MAKE) all

all: coreall
	$(MAKE) ocaml
	$(MAKE) otherlibraries $(WITH_DEBUGGER) $(WITH_OCAMLDOC) \
         $(WITH_OCAMLTEST)

ocaml$(EXE): $(expunge) ocaml.tmp
	- $(OCAMLRUN) $^ $@ $(PERVASIVES)

otherlibraries: ocamltools
	$(MAKE) -C otherlibs all

ocamltools: ocamlc ocamllex compilerlibs/ocamlmiddleend.cma
	$(MAKE) -C tools all

```

NOTE: `compilerlibs` is an empty pseudo-package, just used
quasi-namespacing; OBazl does not need it. So e.g. the target to build
`compilerlibs/ocamlmiddleend.cma` is `//middle_end:ocamlmiddleend`

=== make coldstart

Builds `runtime/ocamlrun`(Bazel target: `//boot:ocamlrun`) and stdlib (Bazel: `//stdlib`)

.root Makefile
```
USE_RUNTIME_PRIMS = -use-prims ../runtime/primitives

  COLDSTART_DEPS =
  BOOT_FLEXLINK_CMD =

OCAMLRUN ?= $(ROOTDIR)/boot/ocamlrun$(EXE)  (Makefile.common)
BOOT_OCAMLC = $(OCAMLRUN) $(ROOTDIR)/boot/ocamlc (Makefile.common)

coldstart: $(COLDSTART_DEPS)
	$(MAKE) -C runtime all
	$(MAKE) -C stdlib \
	  OCAMLRUN='$$(ROOTDIR)/runtime/ocamlrun$(EXE)' \
	  CAMLC='$$(BOOT_OCAMLC) $(USE_RUNTIME_PRIMS)' all

NB: `make -C runtime all` builds `runtime/ocamlrun` using MKEXE;
then `make -C stdlib all` uses `runtime/ocamlrun boot/ocamlc` to build stdlib.
later `runtime/ocamlrun` gets copied to `boot/ocamlrun`
```

=== make coreall

`make world` builds `make coldstart` then `make coreall`, which:

* builds `runtime/libcamlrun` and copies it to `stdlib/libcamlrun`
* builds `ocamlc`, `ocamllex`, etc.

WARNING: With OBazl we do not need to copy `libocamlrun` into `stdlib`
directory, since our dependency manager will ensure that everything
needed for each target will always be in the right place. Makefiles
control accessibility using ordered search paths. With Bazel we
control inputs before we even get constructing the command line, and
then we put those input dirs on the search path. So if we need
`libocamlrun` we just list it as a dependency, and it does not matter
where it is located.

.root Makefile
```
coreall: runtime
	$(MAKE) ocamlc
	$(MAKE) ocamllex ocamltools library

makeruntime:
	$(MAKE) -C runtime $(BOOT_FLEXLINK_CMD) all
runtime/libcamlrun.$(A): makeruntime ;
stdlib/libcamlrun.$(A): runtime/libcamlrun.$(A)
	cd stdlib; $(LN) ../runtime/libcamlrun.$(A) .

runtime: stdlib/libcamlrun.$(A)  # already built by `make -C runtime all` run by `make coldstart`

ocamlc$(EXE): compilerlibs/ocamlcommon.cma \
              compilerlibs/ocamlbytecomp.cma $(BYTESTART)
	$(CAMLC) $(LINKFLAGS) -compat-32 -o $@ $^
ocamllex: ocamlyacc
	$(MAKE) -C lex all
ocamlyacc:
	$(MAKE) -C yacc $(BOOT_FLEXLINK_CMD) all
ocamltools: ocamlc ocamllex compilerlibs/ocamlmiddleend.cma
	$(MAKE) -C tools all
library: ocamlc
	$(MAKE) -C stdlib $(BOOT_FLEXLINK_CMD) all
```


`MKLIB` is set by `configure`; for unix:

`mklib="rm -f \$(1) && ${AR} rc \$(1) \$(2) && ${RANLIB} \$(1)"`

OBazl can ignore MKLIB, since `rules_cc` automatically handles such stuff.

`MKEXE` is set in `Makefile.config`, included via Makefile.common -> Makefile.config_if_required -> Makefile.build_config -> Makefile.config:


.Makefile.config
```
MKEXE=$(CC) $(OC_CFLAGS) $(CFLAGS) $(OC_LDFLAGS) $(LDFLAGS) -Wl,-no_compact_unwind
```

`OC_CFLAGS` etc. - see `config/BUILD.bzl`

=== make runtime

.runtime/Makefile (make -C runtime all)
```
LIBDIR=${exec_prefix}/lib/ocaml
STUBLIBDIR=${exec_prefix}/lib/ocaml/stublibs
ld.conf: $(ROOTDIR)/Makefile.config
	echo "$(STUBLIBDIR)" > $@
	echo "$(LIBDIR)" >> $@

build_config.h: $(ROOTDIR)/Makefile.config sak$(EXE)
	echo '/* This file is generated from $(ROOTDIR)/Makefile.config */' > $@
	echo '#define OCAML_STDLIB_DIR $(call C_LITERAL,$(LIBDIR))' >> $@
	echo '#define HOST "$(HOST)"' >> $@

PROGRAMS := ocamlrun$(EXE)
BYTECODE_STATIC_LIBRARIES := ld.conf libcamlrun.$(A)
BYTECODE_SHARED_LIBRARIES :=

all: $(BYTECODE_STATIC_LIBRARIES) $(BYTECODE_SHARED_LIBRARIES) $(PROGRAMS) \
     sak$(EXE)

primitives: $(shell ./gen_primitives.sh > primitives.new; \
                    cmp -s primitives primitives.new || echo primitives.new)
	cp $^ $@

prims.c : primitives
	(echo '#define CAML_INTERNALS'; \
         echo '#include "caml/mlvalues.h"'; \
         ... etc., more shell cmds ...

BYTECODE_C_SOURCES := ... the c files in `runtime`
libcamlrun_OBJECTS := $(BYTECODE_C_SOURCES:.c=.b.$(O))

libcamlrun.$(A): $(libcamlrun_OBJECTS)
	$(call MKLIB,$@, $^)

BYTECCLIBS= -lm  -lpthread (in Makefile.config)
LIBS := $(BYTECCLIBS)

ocamlrun$(EXE): prims.$(O) libcamlrun.$(A)
	$(MKEXE) -o $@ $^ $(LIBS)

SAK_LINK ?= $(MKEXE_USING_COMPILER)
sak$(EXE): sak.$(O)
	$(call SAK_LINK,$@,$^)

```

=== make -C tools all

all: $(programs_byte)

programs_byte := \
  ocamldep ocamlprof ocamlcp ocamloptp ocamlmklib  \
  ocamlmktop ocamlcmt dumpobj ocamlobjinfo \
  primreq stripdebug cmpbyt


=== make ocaml

`ocaml` is the command to start a repl. The makefiles make it a
root-level target; OBazl puts it in the `toplevel` package, so the
build command is `bazel build toplevel:ocaml`



==  Corresponding OBazl build targets:

* `build_config.h` => `//runtime:build_config_h` (`genrule`)
* `ld.conf`- not needed for Bazel bootstrapping, only for deployment? STUBLIBDIR (ocaml/stublibs) to contain `dll*.so` files from `otherlibs`
* `make -C runtime all` builds `ocamlrun`, `libcamlrun`, `sak`:
  ** `//runtime:camlrun` (`cc_library`)
  ** `//boot:ocamlrun` (`cc_binary`)
  ** `//runtime:sak.exe` (`cc_binary`)
  ** `//runtime:primitives_dat` (`genrule`) => `primitives`
* `make -C stdlib ... all` => `//stdlib` (`bootstrap_archive`)
* `//middle_end:ocamlmiddleend` - archive, instead of `//compilerlibs:ocamlmiddleend`

For root targets like `make ocamlc` we use a pseudo-package
`//compilers`, to make the naming nicer.

* `make ocamlc` => `//compilers:ocamlc`
* `make ocamllex` => `//lex:ocamllex`
* `make ocamltools` =>
* `make library`


== structuring

Its easy to make the OBazl build structure mimic the Makefile-based
structure more-or-less exactly. But where's the fun in that? OBazl's
expressivity allows us to write a much more felicitous build program.
For example, we can put archive targets where they naturally belong,
e.g. `//toplevel:ocamltoplevel`, instead of putting them in an empty
package (//compilelibs) whose only purpose is to provide a common
naming prefix. Even better, we can support both designs by using a
Bazel alias in `//compilerlibs:ocamltoplevel` redirecting to
`//toplevel:ocamltoplevel`.

Furthermore the decoupling of target names from output names allows us
to use more felicitous names. For example, for archive targets the PoC
uses `archive`, and removes some otiose info. Example: for
`//compilerlibs:ocamltoplevel` we have `//toplevel:ocamltoplevel`. We could
also just use the package name, `//toplevel:toplevel`, which shortens
to `//toplevel`. Or `toplevel.archive`, or any other legal Bazel name.

Since `expunge` is a utility, we put it in utils: `//utils:expunge`

== Inspecting build cmds

To see the generated command that Bazel will run, use `aquery`. This
will print the command (and the list of inputs and outputs) without
actually buildig anything.

Archives: to see what's directly included via the command line, use
`aquery` as above. To see what actually gets included (i.e. the deps
as well), run the build and pass `--output_groups=manifest`.

== Stdlib

An interesting feature of OBazl is that we can depend on individual
submodules in a namespace. For example, `utils/config.ml` depends on
`Stdlib.String`. Instead of depending on the Stdlib archive file
(`stdlib.cma`), we can depend ln the String module directly, by label
`//stdlib:Stdlib.String`. So we can build the compiler code without
depending on the Stdlib _archive_, instead depending only on Stdlib
modules. (This is because depending on a namespaced module
automatically injects the needed dependency on the namespace's
resolver (mapping) module.)

== Preprocessing

=== utils/config.ml

Uses a custom rule demonstrating use of Bazel's built-in templating support.

Data is hard-coded.

===  utils/domainstate.ml

*UPDATE* this logic has change in 5.1.x.  The `domainstate.ml.c` file includes:

```
#define CAML_CONFIG_H_NO_TYPEDEFS
#include "config.h"
let stack_ctx_words = Stack_ctx_words
```

which means a simple sed won't work, due to inclusion of config.h.

The makefile is simple:

```
utils/domainstate.ml: utils/domainstate.ml.c runtime/caml/domain_state.tbl
	$(CPP) -I runtime/caml $< > $@

utils/domainstate.mli: utils/domainstate.mli.c runtime/caml/domain_state.tbl
	$(CPP) -I runtime/caml $< > $@
```

CPP is set by ./configure.  On macos, 'clang', apparently.  'cpp' doesn't work.

==== 4.14.0

This is outdated, won't work for 5.1.x.

The Makefile uses CPP to generate `utils/domainstate.ml` from
`utils/domainstate.ml.c` and `runtime/caml/domain_state.tbl` Nutty.
Unfortunately, Bazel's `cc_library` rule insists on inserting various
flags, so the result, even with `-E`, is `error...`

We could define a custom CC toolchain to handle this, which might be
useful for other projects as well. But since this is a simple one-off
task, it makes more sense to generate the file in less unorthodox
manner: a simple sed script in genrule target `utils:domainstate`.

This is the entire content of `utils/domainstate.ml.c`:

```
type t =
#define DOMAIN_STATE(type, name) | Domain_##name
#include "domain_state.tbl"
#undef DOMAIN_STATE

let idx_of_field =
  let curr = 0 in
#define DOMAIN_STATE(type, name) \
  let idx__##name = curr in \
  let curr = curr + 1 in
#include "domain_state.tbl"
#undef DOMAIN_STATE
  let _ = curr in
  function
#define DOMAIN_STATE(type, name) \
  | Domain_##name -> idx__##name
#include "domain_state.tbl"
#undef DOMAIN_STATE
```

This is `runtime/caml/domain_state.tbl`:

```
DOMAIN_STATE(value*, young_limit)
DOMAIN_STATE(value*, young_ptr)
DOMAIN_STATE(char*, exception_pointer)
DOMAIN_STATE(void*, young_base)
DOMAIN_STATE(value*, young_start)
... same, repeated for list of names. note that the `type` field of the macro is not used in `domainstate.ml.c`.
#if defined(NAKED_POINTERS_CHECKER) && !defined(_WIN32)
DOMAIN_STATE(void*, checking_pointer_pc)
/* See major_gc.c */
#endif

DOMAIN_STATE(extra_params_area, extra_params)
/* This member must occur last, because it is an array, not a scalar */
```

Note that this file is `#included` in various other `runtime` assembly files:

runtime/arm.S
129:#include "../runtime/caml/domain_state.tbl"

runtime/arm64.S
63:#include "../runtime/caml/domain_state.tbl"

runtime/i386.S
89:#include "../runtime/caml/domain_state.tbl"

runtime/riscv.S
49:#include "../runtime/caml/domain_state.tbl"

runtime/amd64.S
119:#include "../runtime/caml/domain_state.tbl"

runtime/power.S
148:#include "../runtime/caml/domain_state.tbl"

runtime/s390x.S
32:#include "../runtime/caml/domain_state.tbl"

runtime/caml/domain_state.h
37:#include "domain_state.tbl"
44:#include "domain_state.tbl"

The output (`utils/domainstate.ml`) looks like this:

```
# 1 "utils/domainstate.ml.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 368 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "utils/domainstate.ml.c" 2
# 17 "utils/domainstate.ml.c"
type t =
| Domain_young_limit
| Domain_young_ptr
| Domain_exception_pointer
| Domain_young_base
...
| Domain_extra_params
# 20 "utils/domainstate.ml.c" 2
let idx_of_field =
  let curr = 0 in
# 1 "runtime/caml/domain_state.tbl" 1
# 17 "runtime/caml/domain_state.tbl"
let idx__young_limit = curr in let curr = curr + 1 in
let idx__young_ptr = curr in let curr = curr + 1 in
let idx__exception_pointer = curr in let curr = curr + 1 in
let idx__young_base = curr in let curr = curr + 1 in
let idx__young_start = curr in let curr = curr + 1 in
...

| Domain_extra_params -> idx__extra_params
# 34 "utils/domainstate.ml.c" 2
```

I.e.
* for each entry NM in `domain_state.tbl`, generate Domain_NM
* for each entry NM in `domain_state.tbl`, generate:
  let idx__##name = curr in \
  let curr = curr + 1 in
*  for each entry NM in `domain_state.tbl`, generate:  | Domain_NM -> idx__NM

We should be able to do this with sed or even a shell script.
