= preprocessing

The legacy build uses a variety of shell scripts and tools (awk, sed,
  etc.) to transform and/or generate code. The Bazel build replaces
  all (or at least most) of this with templated code generation using
  an link:https://gitlab.com/jobol/mustach[implementation] of
  link:https://mustache.github.io/mustache.5.html[Mustache] written in
  portable C.

(Some things have not (yet) been replaced, e.g. `lambda/generate_runtimedef.sh`)

CAUTION: This requires some changes to the sources,

Below are some examples. Look for `.mustache` and `.json` files in the
sources; the process is driven by a custom Bazel rule named
`mustache`.

=== Domain state

File `runtime/caml/domain_state.tbl` is replaced by
`domain_state.json`, and `runtime/caml/domain_state.h` is generated
from that and a template, `runtime/caml/domain_state.h.mustache`.
Similarly for other files generated from `domain_state.tbl`. I believe
the result is much simpler and clearer.


=== Opcodes and opnames

The legacy build parses `runtime/caml/instruct.h` to extract
information about opcodes. It uses an OCaml program (a lexer) to do
this (tools/make_opcodes), which of course must be built. This is
overkill - its job is very simple, parse the enum in
`runtime/caml:instruct.h`. OBazl eliminates this, instead using a json
file to drive code generation from mustache templates. The result is
much simpler, IMO.

The following files are generated by template from `bytecomp:opcodes.json`:

** `bytecomp/opcodes.ml`
** `bytecomp/opnames.ml`
** `runtime/caml/instruct.h`
** `runtime/caml/jumptbl.h`
** `runtime/caml/opnames.h`

You can obtain this list by running the following query:

    bazel query "rdeps(//..., //bytecomp:opcodes.json, 1)"

Change '1' to '2' to see two levels of dependency:

----
$ bazel query "rdeps(//..., //bytecomp:opcodes.json, 2)"
//bytecomp:Opcodes
//bytecomp:opcodes.json
//bytecomp:opcodes.ml
//bytecomp:opcodes_ml
//bytecomp:opnames.ml
//bytecomp:opnames_ml
//runtime:camlrun
//runtime:ocamlrun
//runtime/caml:instruct_h
//runtime/caml:jumptbl_h
//runtime/caml:opnames_h
----

This tells us that both `libcamlrun.a` and `ocamlrun` depend on
`//bytecomp:opcodes.json`, which means that every VM executable will
also depend on it.

=== Primitives

See xref:primitives.adoc[Primitives].
