= build protocols

== boot protocol:  //bin

Compiler targets in the `//bin` package are built directly from
`/boot/ocamlc`. The boot build protocol does not bootstrap to reach a
fixed point, on the assumption that `boot/camlc` and the sources are
already there. So they are only appropriate for release commits, where
the source code matches `boot/ocamlc`. This would be the case where
the user just wants to build the compilers from a source release for use in a
project.

== baseline protocol: //boot

Compiler targets in the `//boot` package build recursively to reach a
fixed point. The `//boot:coldstart` run target saves the built images
to `.baseline`, where they are used for compiler development.

== test protocol:  //testsuite

Targets in the testsuite build under the `test` protocol. The builds
use the baseline compilers built by running `//boot:coldstart` to
build new versions of the compilers, incorporating any changes in the
source code, and then use the new versions to build the test cases.

