= toolchains



Toolchain resolution is a little complicated. Details at link:https://bazel.build/configure/toolchain-resolution[Toolchain Resolution Implementation Details]


Key point: "[T]he dependency from a target to a toolchain uses a
special configuration that forces the execution platform to be the
same for both. Despite the name "toolchain transition", this is not
implemented as a configuration transition..."

This seems to be a little more up to date:  link:https://bazel.build/extending/toolchains#toolchain-resolution[Toolchain resolution]

WARNING: CLI options ` --extra_execution_platforms` and `--host_platform` do not have the same effect.



https://bazel.build/reference/be/common-definitions#common-attributes

`exec_compatible_with` on rules:

"A list of constraint_values that must be present in the execution
platform for this target. This is in addition to any constraints
already set by the rule type. Constraints are used to restrict the
list of available execution platforms."
