= tools
:toc: auto
:toclevels: 3


See also xref:tool_runners.adoc[Tool runners].

== developer tools

Each tool has two build targets, *.byte and *.opt. An alias for
the *.opt version is defined for each; e.g. `:ocamldep` is aliased to `:ocamldep.opt`.

Tool _build_ targets are defined in several packages:

* `//tools` - e.g. `//tools:ocamldep.byte`. These targets are built
  under the standard xref:build_protocols.adoc[build protocol] (i.e.
  starting with `boot/ocamlc` and without any recursive bootstrapping
  steps).

* `@dev//bin` - e.g. `@dev//bin:ocamldep.byte`. These targets are
  availabel after you run [nowrap]`bazel run boot:checkpoint`. They
  run the compiled tools in `@dev` (i.e. in `.baseline/bin`), which
  are built (by [nowrap]`boot:checkpoint`) under the `boot` build
  protocol. In other words, running these targets does _not_ rebuild
  the tools.

* `//test` - e.g. `//test:ocamldep.byte`. These targets are built
  under the `test` build protocol, which means they will be rebuilt
  (incrementally, if the sources change) starting from
  `@dev//bin:ocamlc.opt` or `@dev//bin:ocamlopt.opt`. Use these
  targets if you are changing the tools themselves, or if you make
  changes to the compiler sources or stdlib and you want the tools to
  used those changes.

=== Usage

Each tool has an associated xref:tool_runners.adoc[tool runner]
target. These must have different names than the build targets;
otherwise we get name clashes that Bazel disallows.

Each tool takes an argument which may be a source file (`ocamldep`), a
compiled object or archive file (`ocamlobjinfo`), or a compiled `.cmt`
file (`ocamlcmt`). To use the tool runners, these arguments must be
passed using `--//:arg=<argument>`. This is inconvenient, but not
overly so, and it has the virtue of integrating the arguments into the
Bazel context. This is needed because `bazel run //pkg:tgt` does not
launch the `:tgt` executable from the project root directory from
which you run `bazel run`. Instead it switches to a Bazel internal
directory, which you can see by running `$ bazel info execution_root`
or passing `--//tools:verbose` with your `bazel run` command.. This
means you cannot pass the tool paths relative to the project root.

You could pass absolute paths, but that would only work for source
file arguments. For compiled object arguments, you would have to
discover where Bazel puts them. For example, if you build
`testsuite/tests/basic/_BS_vv/Arrays`, the output will go somewhere
like:

    bazel-out/darwin-fastbuild-ST-96fabab2dcd0/bin/testsuite/tests/basic/_BS_vv/Arrays.cmo

The tool runners are designed to find such paths if you pass them a
Bazel build label using `--//:arg=<argument>`. For example to inspect
`Arrays.cmo`:

    bazel run @dev//bin:ocamlobjinfo --//:arg=//testsuite/tests/basic:Arrays --//tools:verbose

This runs `.baseline/bin/ocamlobjinfo.opt`

To save a little typing (no pun intended), each tool also has one or
more aliases. In no particular order:

=== ocamlcmt

Aliases:  `cmt`, `lst` (list types)

    bazel run @dev//bin:cmt --//:arg=//bytecomp:Bytegen
    bazel run @dev//bin:cmt --//:arg=//bytecomp:Bytegen_cmi

The toolrunner dynamically configures the build to add
`--//config/ocaml/compile:bin-annot`, which tells the build rules to
add `-bin-annot`.

It can also determined if the argument is a module or a signature
target, and accordingly find the `.cmt` or `.cmti` file.

=== ocamldep

Alias:  `deps`

    bazel run @dev//bin:deps --//:arg=//typing:Ident
    bazel run @dev//bin:deps --//:arg=//typing:ident.ml
    bazel run @dev//bin:deps --//:arg=//typing:Ident_cmi
    bazel run @dev//bin:deps --//:arg=//typing:ident.mli

Runs `.baseline/lib/ocamldep.opt`

The tool runner understands both Bazel build target labels and source
file labels (but notice the difference in case: `Ident` v.
`ident.ml`).

WARNING: Source file labels are almost the same as file system paths,
but the last segment separator must be a colon `:` intead of a solidus
`/`. E.g. `//typing:ident.ml` instead of `//typing/ident.ml`. Asc
noted you cannot simply pass a path relative to the project root;
however in this case it will work with `--//:arg`, because Bazel will
interpret `typing:ident.ml` as label `//typing:ident.ml`, not as a
file system path:

    azel run @dev//bin:deps --//:arg=typing:ident.mli

=== ocamlobjinfo

Aliases:  `lso` (list object)

    bazel run @dev//bin:lso --//:arg=//stdlib:Stdlilb.Buffer
    bazel run @dev//bin:lso --//:arg=//stdlib:Stdlilb.Buffer

Runs `.baseline/lib/ocamlobjinfo.opt`

=== dumpobj

=== primreq

Alias:  `lsp` (list primitives)

----
    bazel run @dev//bin:lsp --//:arg=//bytecomp:Meta
    ...
    INFO: Running command line: bazel-bin/external/dev/bin/primreq.sh
    caml_get_global_data
    caml_get_section_table
    caml_invoke_traced_function
    caml_realloc_global
    caml_reify_bytecode
    caml_static_release_bytecode
----

Runs `.baseline/bin/primreq.opt`

== obsolete

The following stuff is a little outdated but may be useful.

=== run targets

As a convenience, targets have been defined in the root package, to minimize keystrokes:

* bazel run :deps - runs @dev//bin:ocamldep.opt
* bazel run :lso - runs @dev//bin:ocamlobjinfo.opt  (`:lso` == list object)
* bazel run :lsp - runs @dev//bin:primreqs.opt (`:lsp` == list primitives)
* bazel run :cmt - runs @dev//bin:ocamlcmt.opt

=== build targets

NB: the leading `//` may be omitted in build commands, e.g. `$ bazel
build tools:ocamldep` is equivalent to [.nowrap]`$ bazel build //tools:ocamldep`.

* `//tools:ocamldep` - compute dependencies

* `//tools:cmpbyt` - compare two bytecode executables

Inspection:

* `//tools:ocamlcmt` - dump `.cmt`, `.cmti` files
* `//tools:ocamldumpobj` - dissasembler for executable and .cmo object files
* `//tools:ocamlobjinfo` - dump `.cmo`, `.cmx`, `.cma`, `.cmxa` files
  ** alias:  :lso  (ls object)
* `//tools:primreq` - determine the set of C primitives used by `.cmo`, `.cma` files

Build tools:

* `//tools:stripdebug` - copy bytecode executable, removing debug info and #! header

These two  are not needed with Bazel:

* `//tools:ocamlmklib` - facilitates the construction of libraries containing both OCaml code and C code (link:https://v2.ocaml.org/manual/intfc.html#s%3Aocamlmklib[Building  mixed C/OCaml libraries: ocamlmklib]
* `//tools:ocamlmktop` -  builds OCaml toplevels that contain user code preloaded at start-up.  link:https://v2.ocaml.org/manual/toplevel.html#s%3Acustom-toplevel[Building custom toplevel systems: ocamlmktop
]

The OCaml profiling compilers are in the `//bin` package:

* `//bin:ocamlcp.byte`, `//bin:ocamlcp.opt`
* `//bin:ocamloptp.byte`, `//bin:ocamloptp.opt`

link:https://v2.ocaml.org/manual/profil.html[Profiling]:

* `//tools:ocamlprof` -  prints execution counts gathered during the execution of a OCaml program instrumented with ocamlcp


=== running tools under bazel

Special support for:  ocamldep, ocamlobjinfo, dumpobj, primreq.


To run a tool directly on the command line, you must first build it
and then construct a command line. This requires that you figure out
where Bazel has saved things. For example:

    .baseline/bin/ocamlrun ./bazel-bin/tools/_dev_boot/ocamlcmt.byte bazel-bin/stdlib/_dev_boot/Stdlib__Weak.cmt

This is too cumbersome to be useful, but fortunately you can use Bazel
to run the executables it builds. Executable targets can always be run
under bazel, e.g. `$ bazel run path/to:target`. However this still
requires that you provide the appropriate arguments as in the above
example, so it only partially solves the problem. For example, to run
`ocamlobjinfo` on Stdlib.Buffer the command would look like this:

    $ bazel run tools:ocamlobjinfo -- $PWD/bazel-bin/stdlib/_dev_boot/Stdlib__Buffer.cmo

This is still cumbersome, and requires that you first build the target
in order to discover the correct path.

As a convenience, the following targets are designed to automatically
configure the command line needed. They write the constructed command
line to a shell script that Bazel then executes. You pass them the
Bazel label of the intended file, and they convert it to the
appropriate filesystem path. They will also rebuild either the tool or
the argument if the sources for either have changed:

* `//tools:ocamldep.opt.sh`
* `//tools:dumpobj.byte.sh`
* `//tools:dumpobj.obj.sh`
* `//tools:ocamlcmt.sh`
* `//tools:ocamlobjinfo.byte.sh`
* `//tools:ocamlobjinfo.opt.sh`
* `//tools::primreq.sh`

The leading `//` may be omitted. These targets take label arguments of the following form:

    `--//:arg=<path to target`>

Here `<path to target>` is a Bazel label, which the rules will convert
to the correct filesystem path.

Examples:

* Inspect `Stdlib__Buffer.cmo` using `ocamlobjinfo`:

    $ bazel run tools:ocamlobjinfo.opt.sh --//:arg=//stdlib:Stdlib.Buffer

* List dependencies of `testsuite/tests/basic:sets.ml`

    $ bazel run tools:ocamldep.opt.sh --//:arg=testsuite/tests/basic:sets.ml
+
NOTE: Notice the colon in `basic:sets.ml`. This is a Bazel label, not
a file system path.


As a convenience, aliases are defined in the root package:
`//:ocamlobjinfo` is aliased to `tools:ocamlobjinfo`, etc. Saves a
little typing.

Show the primitives used by `Stdlib.Bool`:

[source%nowrap,shell]
----
$ bazel run :primreq --//:arg=//stdlib:Stdlib.Bool -- -used
INFO: Analyzed target //:primreq (0 packages loaded, 2062 targets configured).
INFO: Found 1 target...
Target //:primreq up-to-date:
  bazel-bin/primreq.sh
INFO: Elapsed time: 0.422s, Critical Path: 0.14s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/primreq.sh -used
caml_hash
caml_int_compare
----

[NOTE]
====
You can cut down the amount of output by passing
`--ui_event_filters=-info` and `--noshow_progress`:
[source%nowrap,shell]
----
$ bazel run :primreq --noshow_progress --ui_event_filters=-info --//:arg=//stdlib:Stdlib.Bool -- -used
Target //:primreq up-to-date:
  bazel-bin/primreq.sh
caml_hash
caml_int_compare
----
====

Most of the tools take various additional arguments (such as `-I path`). Pass such arguments after a double-hypen `--`; e.g.

    $ bazel run :ocamlobjinfo -- -help
    $ bazel run :ocamlobjinfo --//:arg=//stdlib:Stdlib.Buffer -- -null-crc
    $ bazel run :primreq --//:arg=//stdlib:Stdlib.Bool -- -used

CAUTION: the `--//:arg` argument must come before the `--`.

To see the generated command pass `--//config/tools:verbose` (before `--`):

    $ bazel run :ocamlobjinfo --//:arg=//stdlib:Stdlib.Buffer --//config/tools:verbose -- -null-crc

== Utilities

Bazel's query facilities are powerful but cumbersome. For commonly
used queries a shell script makes sense.

* Macro expansion:

.~/bin/bzlmacro
----
#!/bin/sh
bazel query "attr(generator_name, $1, $2...)" --output=build
----
